# Generated by Django 4.2.17 on 2024-12-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0011_delete_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_url", models.CharField()),
                ("display_name", models.CharField(blank=True, null=True)),
                ("pings", models.IntegerField(default=0)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="clubs.club",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="qrcode",
                        serialize=False,
                        to="analytics.link",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.models.UploadFilepathFactory("clubs/qrcodes/"),
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code",
            },
        ),
        migrations.CreateModel(
            name="LinkVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ipaddress", models.GenericIPAddressField()),
                ("context", models.JSONField(blank=True, null=True)),
                ("amount", models.IntegerField(default=1)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="analytics.link",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="linkvisit",
            constraint=models.UniqueConstraint(
                fields=("link", "ipaddress"), name="unique_ip_per_link"
            ),
        ),
    ]
