# Generated by Django 4.2.17 on 2024-12-25 21:11

from django.db import migrations
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="link",
            field=utils.models.OneToOneOrNoneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="qrcode",
                serialize=False,
                to="analytics.link",
            ),
        ),
    ]
