# Generated by Django 4.2.17 on 2024-12-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_qrcode_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkvisit",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
