# Generated by Django 4.2.18 on 2025-02-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_linkvisit_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="pings",
        ),
        migrations.AlterField(
            model_name="linkvisit",
            name="amount",
            field=models.IntegerField(
                default=0, help_text="Number of times this person clicked the link"
            ),
        ),
        migrations.AlterField(
            model_name="linkvisit",
            name="context",
            field=models.JSONField(
                blank=True, help_text="Extra meta information", null=True
            ),
        ),
        migrations.AlterField(
            model_name="linkvisit",
            name="ipaddress",
            field=models.GenericIPAddressField(
                help_text="IP Address of the person that visited the link"
            ),
        ),
    ]
