# Generated by Django 4.2.16 on 2024-09-28 22:09

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user/profile.jpeg",
                upload_to=utils.models.UploadFilepathFactory("users/profiles/"),
            ),
        ),
    ]
