# Generated by Django 4.2.16 on 2024-11-18 15:08

from django.db import migrations


def migrate_sync_user_email(apps, schema_editor):
    """Sync email field with new username."""
    User = apps.get_model("users", "User")
    users = User.objects.all()

    for user in users:
        user.email = user.username
        user.save()


def migrate_reverse_sync_user_email(apps, schema_editor):
    """Remove all emails from profiles."""
    User = apps.get_model("users", "User")
    users = User.objects.all()

    for user in users:
        user.email = None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RunPython(migrate_sync_user_email, migrate_reverse_sync_user_email)
    ]
