# Generated by Django 4.2.16 on 2024-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_manual_sync_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=32, unique=True),
        ),
    ]
