# Generated by Django 4.2.19 on 2025-02-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="choiceinputoption",
            name="unique_choiceoption_order_per_input",
        ),
        migrations.RemoveConstraint(
            model_name="pollfield",
            name="unique_field_order_per_poll",
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="multiple_choice_type",
            field=models.CharField(
                blank=True,
                choices=[("select", "Select Box"), ("checkbox", "Checkbox Select")],
                default="checkbox",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_choice_input",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="single_choice_type",
            field=models.CharField(
                blank=True,
                choices=[("select", "Dropdown Select"), ("radio", "Radio Select")],
                default="radio",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rangeinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_range_input",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="textinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_text_input",
                to="polls.pollquestion",
            ),
        ),
        migrations.AlterField(
            model_name="textinput",
            name="text_type",
            field=models.CharField(
                choices=[
                    ("short", "Short Text Input"),
                    ("long", "Long Text Input"),
                    ("rich", "Rich Text Input"),
                ],
                default="short",
            ),
        ),
        migrations.AlterField(
            model_name="uploadinput",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_upload_input",
                to="polls.pollquestion",
            ),
        ),
    ]
