# Generated by Django 4.2.19 on 2025-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "polls",
            "0002_remove_choiceinputoption_unique_choiceoption_order_per_input_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choiceinput",
            options={"ordering": ["question__field", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="choiceinputoption",
            options={"ordering": ["order", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="pollfield",
            options={"ordering": ["order", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="pollquestion",
            options={"ordering": ["field", "-id"]},
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="multiple_choice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("select", "Multi Select Box"),
                    ("checkbox", "Multi Checkbox Select"),
                ],
                default="checkbox",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="choiceinput",
            name="single_choice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("select", "Single Dropdown Select"),
                    ("radio", "Single Radio Select"),
                ],
                default="radio",
                null=True,
            ),
        ),
    ]
