# Generated by Django 4.2.19 on 2025-02-24 03:18

import django.core.validators
from django.db import migrations, models
import rest_framework.serializers
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueryCsvUploadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=utils.models.UploadFilepathFactory(
                            default_extension="csv", path="core/querycsv/uploads/"
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("csv", "xls", "xlsx")
                            )
                        ],
                    ),
                ),
                (
                    "serializer",
                    models.CharField(
                        max_length=64,
                        null=True,
                        validators=[
                            utils.models.ValidateImportString(
                                target_type=rest_framework.serializers.Serializer
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("success", "Success"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "notify_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "report",
                    models.FileField(
                        blank=True, null=True, upload_to="core/querycsv/reports/"
                    ),
                ),
                (
                    "custom_field_mappings",
                    models.JSONField(
                        blank=True,
                        help_text="Key value pairs, column name => model field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
