# Generated by Django 4.2.19 on 2025-02-24 23:43

from django.db import migrations, models
import querycsv.serializers
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("querycsv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querycsvuploadjob",
            name="serializer",
            field=models.CharField(
                max_length=64,
                null=True,
                validators=[
                    utils.models.ValidateImportString(
                        target_type=querycsv.serializers.CsvModelSerializer
                    )
                ],
            ),
        ),
    ]
