# Generated by Django 4.2.16 on 2024-09-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
