# Generated by Django 4.2.16 on 2024-09-28 22:09

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0003_clubmembership_owner_alter_clubmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.models.UploadFilepathFactory("clubs/logos/"),
            ),
        ),
    ]
