# Generated by Django 4.2.16 on 2024-10-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_event_eventattendance_recurringevent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clubmembership",
            old_name="points",
            new_name="coins",
        ),
    ]
