# Generated by Django 4.2.16 on 2024-10-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_rename_points_clubmembership_coins"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="clubmembership",
            old_name="coins",
            new_name="points",
        ),
    ]
