# Generated by Django 4.2.16 on 2024-12-05 05:52

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0007_qrcode_rename_coins_clubmembership_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.models.UploadFilepathFactory("clubs/qrcodes/"),
            ),
        ),
    ]
