# Generated by Django 4.2.16 on 2024-12-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0008_alter_qrcode_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrcode",
            options={"verbose_name": "QR Code"},
        ),
    ]
