# Generated by Django 4.2.18 on 2025-02-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_remove_link_pings_alter_linkvisit_amount_and_more"),
        ("clubs", "0011_delete_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAttendanceLink",
            fields=[
                (
                    "link_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="analytics.link",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Used to differentiate between links",
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_links",
                        to="clubs.event",
                    ),
                ),
            ],
            bases=("analytics.link",),
        ),
        migrations.AddConstraint(
            model_name="eventattendancelink",
            constraint=models.UniqueConstraint(
                fields=("event", "reference"),
                name="unique_reference_per_event_attendance_link",
            ),
        ),
    ]
