# Generated by Django 4.2.19 on 2025-02-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0013_team_teammembership"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("club", "name"), name="unique_team_per_club"
            ),
        ),
    ]
