# Generated by Django 4.2.19 on 2025-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0014_team_unique_team_per_club"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("user", "team"), name="user_single_team_membership"
            ),
        ),
    ]
