# Generated by Django 4.2.19 on 2025-02-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("clubs", "0015_teammembership_user_single_team_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={
                "permissions": [
                    ("preview_club", "Can view a set of limited fields for a club.")
                ]
            },
        ),
        migrations.RemoveField(
            model_name="clubmembership",
            name="role",
        ),
        migrations.CreateModel(
            name="ClubRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default",
                    models.BooleanField(
                        default=False,
                        help_text="New members would be automatically assigned this role.",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="clubs.club",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clubmembership",
            name="roles",
            field=models.ManyToManyField(to="clubs.clubrole"),
        ),
        migrations.AddConstraint(
            model_name="clubrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default", "club"),
                name="only_one_default_club_role_per_club",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubrole",
            constraint=models.UniqueConstraint(
                fields=("name", "club"), name="unique_rolename_per_club"
            ),
        ),
    ]
