# Generated by Django 4.2.19 on 2025-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0016_alter_club_options_remove_clubmembership_role_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubrole",
            name="only_one_default_club_role",
        ),
        migrations.AddConstraint(
            model_name="clubrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default", True)),
                fields=("default", "club"),
                name="only_one_default_club_role_per_club",
            ),
        ),
    ]
