# Generated by Django 4.2.19 on 2025-02-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0016_alter_club_options_remove_clubmembership_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="access",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("team", "Team"),
                    ("org", "Org"),
                    ("closed", "Closed"),
                ],
                default="open",
            ),
        ),
    ]
